### ISSUE TITLE
Coluna anime avaliado nunca é atualizada

### ISSUE THREAD

**Issue by Victor-Saraiva-P** [brunagcferreira/myufapeanime#11]
![image](https://github.com/user-attachments/assets/4eb57832-faa4-4bde-b8b0-f31cdb6eb10e)
Outros detalhes que ainda falta implementar, não sei se tu já pretendia fazer isso (mas enf vale citar):

- mesmo usuario não poder fazer duas avaliações no mesmo anime
- permitir que a avaliação tenha um id de usuario ou de anime que não existe
- garantir que notas estejam entre 0 <= nota <= 10

**Comment by JorgRibeiro** [comment]
Corrigi tudo e adicionei mais alguns tratamentos de erros, vou mandar o pull request
